# Generated by Django 3.1.6 on 2022-06-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220605_0018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicPosts',
            new_name='PublicPost',
        ),
    ]
