# Generated by Django 3.1.6 on 2022-06-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220605_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicpost',
            old_name='post_id',
            new_name='user_id',
        ),
    ]
