# Generated by Django 3.1.6 on 2022-08-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='mobile',
        ),
    ]
